In [1]:
import numpy as np

In [2]:
Inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]
Inputs

[[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]

In [3]:
Weights = [[.2,.8,-.5,1],
           [.5,-.91,.26,-.5],
           [-.26,-.27,.17,.87]]
Weights

[[0.2, 0.8, -0.5, 1], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

In [4]:
Biases = [2,3,.5]
Biases

[2, 3, 0.5]

In [5]:
np.dot(Inputs,np.array(Weights).T)

array([[ 2.8  , -1.79 ,  1.885],
       [ 6.9  , -4.81 , -0.3  ],
       [-0.59 , -1.949, -0.474]])

In [6]:
np.dot(Inputs,np.array(Weights).T) + Biases

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

## Now we add another Layer

In [7]:
Weights2 = [[0.1,-.14,.5],
            [-.5,.12,-.33],
            [-.44,.73,-.13]]
Weights2

[[0.1, -0.14, 0.5], [-0.5, 0.12, -0.33], [-0.44, 0.73, -0.13]]

In [9]:
Biases2 = [-1,2,-.5]
Biases2

[-1, 2, -0.5]

### Input to the layer 2 is output of the layer 1

In [12]:
layer2_input = np.dot(Inputs,np.array(Weights).T) + Biases
layer2_input

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [13]:
np.dot(layer2_input,np.array(Weights2).T)

array([[ 1.5031 , -3.04185, -1.53875],
       [ 1.2434 , -4.7332 , -5.2633 ],
       [ 0.00686, -0.58746,  0.14345]])

In [14]:
np.dot(layer2_input,np.array(Weights2).T) + Biases2

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])