In [9]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [10]:
nnfs.init()

In [11]:
X, y = spiral_data(samples=100,classes=3)

In [12]:
class Layer_Dense :
    def __init__(self,n_inputs,n_neurons):
        self.Weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.Biases = np.zeros((1,n_neurons))
    def forward(self,inputs) :
        self.output = np.dot(inputs,self.Weights) + self.Biases

In [13]:
class Activation_ReLU :
    def forward(self,inputs) :
        self.output = np.maximum(0,inputs)

In [14]:
class Activation_Softmax :
    def forward(self,inputs) :
        exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1,keepdims=True)
        self.output = probabilities

In [24]:
class Loss :
    def calculate(self, output, y) :
        sample_losses = self.forward(output,y)
        data_loss = np.mean(sample_losses)
        return data_loss

In [29]:
class LCC(Loss) :
    def forward(self,y_pred,y_true) :
        samples = len(y_pred)
        y_pred_cliped = np.clip(y_pred,1e-7,1-1e-7)
        
        if len(y_true.shape) == 1 :
            correct_confidence = y_pred_cliped[range(samples),y_true]
            
        elif len(y_true.shape) == 2 :
            correct_confindence = np.sum(y_pred_cliped*y_true,axis=1)
            
        negative_log_likelyhoods = -np.log(correct_confidence)
        
        return negative_log_likelyhoods

In [18]:
layer1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

layer2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

In [19]:
layer1.forward(X)

In [27]:
layer1.output

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.73345644e-04,  8.62696557e-04,  1.39679760e-03],
       [-1.49897707e-03,  1.26489194e-03,  4.06971667e-03],
       [-1.24954700e-03, -5.30321013e-05,  7.09683774e-03],
       [-1.88506208e-03,  2.60072527e-04,  9.56873316e-03],
       [-3.58449691e-03,  4.75023361e-03,  3.96021409e-03],
       [-3.67908739e-03,  1.84562709e-03,  1.41997067e-02],
       [-5.32548083e-03,  4.72563878e-03,  1.36832986e-02],
       [-5.87350968e-03,  4.66894405e-03,  1.69076808e-02],
       [-5.37187001e-03,  2.49263644e-03,  2.14094073e-02],
       [-6.12692488e-03,  3.06672161e-03,  2.36703008e-02],
       [-1.27728051e-03, -4.45934711e-03,  2.19892077e-02],
       [-3.59788723e-03, -2.16038898e-03,  2.71498784e-02],
       [-5.83126210e-03,  3.91844078e-04,  3.09803132e-02],
       [-3.75679834e-03, -3.09499633e-03,  3.11560519e-02],
       [-3.51769337e-03, -3.96001106e-03,  3.27254012e-02],
       [ 4.56575630e-03, -1.26439845e-02

In [20]:
activation1.forward(layer1.output)

In [29]:
activation1.output

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.62696557e-04, 1.39679760e-03],
       [0.00000000e+00, 1.26489194e-03, 4.06971667e-03],
       [0.00000000e+00, 0.00000000e+00, 7.09683774e-03],
       [0.00000000e+00, 2.60072527e-04, 9.56873316e-03],
       [0.00000000e+00, 4.75023361e-03, 3.96021409e-03],
       [0.00000000e+00, 1.84562709e-03, 1.41997067e-02],
       [0.00000000e+00, 4.72563878e-03, 1.36832986e-02],
       [0.00000000e+00, 4.66894405e-03, 1.69076808e-02],
       [0.00000000e+00, 2.49263644e-03, 2.14094073e-02],
       [0.00000000e+00, 3.06672161e-03, 2.36703008e-02],
       [0.00000000e+00, 0.00000000e+00, 2.19892077e-02],
       [0.00000000e+00, 0.00000000e+00, 2.71498784e-02],
       [0.00000000e+00, 3.91844078e-04, 3.09803132e-02],
       [0.00000000e+00, 0.00000000e+00, 3.11560519e-02],
       [0.00000000e+00, 0.00000000e+00, 3.27254012e-02],
       [4.56575630e-03, 0.00000000e+00, 1.70099996e-02],
       [0.00000000e+00, 0.00000

In [21]:
layer2.forward(activation1.output)

In [31]:
layer2.output.shape

(300, 3)

In [22]:
activation2.forward(layer2.output)

In [33]:
activation2.output

array([[0.33333334, 0.33333334, 0.33333334],
       [0.33329222, 0.3333333 , 0.33337447],
       [0.33327144, 0.33325514, 0.33347347],
       [0.33332744, 0.33305907, 0.33361349],
       [0.3333133 , 0.33297983, 0.33370686],
       [0.3331101 , 0.3334773 , 0.33341262],
       [0.333236  , 0.33289996, 0.33386406],
       [0.33310318, 0.3330999 , 0.33379695],
       [0.33310306, 0.33297172, 0.33392525],
       [0.33319983, 0.33266187, 0.33413833],
       [0.33317128, 0.33261037, 0.33421835],
       [0.3333146 , 0.3324838 , 0.3342016 ],
       [0.33330995, 0.33228454, 0.33440548],
       [0.3332884 , 0.33216107, 0.33455053],
       [0.33330634, 0.33212984, 0.33456382],
       [0.3333049 , 0.33206925, 0.33462584],
       [0.33321938, 0.33287475, 0.33390588],
       [0.33329988, 0.33185974, 0.33484036],
       [0.33330524, 0.33208218, 0.33461258],
       [0.33329406, 0.33162236, 0.3350835 ],
       [0.33274814, 0.33245265, 0.33479923],
       [0.3331594 , 0.33293772, 0.3339029 ],
       [0.

In [30]:
loss_fun = LCC()
loss = loss_fun.calculate(activation2.output,y)

In [31]:
loss

1.098445

In [32]:
activation2.output.shape

(300, 3)

In [33]:
y.shape

(300,)