In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [2]:
nnfs.init()

In [3]:
X, y = spiral_data(samples=100,classes=3)

In [4]:
class Layer_Dense :
    def __init__(self,n_inputs,n_neurons):
        self.Weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.Biases = np.zeros((1,n_neurons))
    def forward(self,inputs) :
        self.output = np.dot(inputs,self.Weights) + self.Biases

In [5]:
class Activation_ReLU :
    def forward(self,inputs) :
        self.output = np.maximum(0,inputs)

In [6]:
class Activation_Softmax :
    def forward(self,inputs) :
        exp_values = np.exp(inputs - np.max(inputs,axis=1,keepdims=True))
        probabilities = exp_values / np.sum(exp_values, axis=1,keepdims=True)
        self.output = probabilities

In [7]:
layer1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()

layer2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

In [8]:
layer1.forward(X)

In [27]:
layer1.output

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-7.73345644e-04,  8.62696557e-04,  1.39679760e-03],
       [-1.49897707e-03,  1.26489194e-03,  4.06971667e-03],
       [-1.24954700e-03, -5.30321013e-05,  7.09683774e-03],
       [-1.88506208e-03,  2.60072527e-04,  9.56873316e-03],
       [-3.58449691e-03,  4.75023361e-03,  3.96021409e-03],
       [-3.67908739e-03,  1.84562709e-03,  1.41997067e-02],
       [-5.32548083e-03,  4.72563878e-03,  1.36832986e-02],
       [-5.87350968e-03,  4.66894405e-03,  1.69076808e-02],
       [-5.37187001e-03,  2.49263644e-03,  2.14094073e-02],
       [-6.12692488e-03,  3.06672161e-03,  2.36703008e-02],
       [-1.27728051e-03, -4.45934711e-03,  2.19892077e-02],
       [-3.59788723e-03, -2.16038898e-03,  2.71498784e-02],
       [-5.83126210e-03,  3.91844078e-04,  3.09803132e-02],
       [-3.75679834e-03, -3.09499633e-03,  3.11560519e-02],
       [-3.51769337e-03, -3.96001106e-03,  3.27254012e-02],
       [ 4.56575630e-03, -1.26439845e-02

In [9]:
activation1.forward(layer1.output)

In [29]:
activation1.output

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 8.62696557e-04, 1.39679760e-03],
       [0.00000000e+00, 1.26489194e-03, 4.06971667e-03],
       [0.00000000e+00, 0.00000000e+00, 7.09683774e-03],
       [0.00000000e+00, 2.60072527e-04, 9.56873316e-03],
       [0.00000000e+00, 4.75023361e-03, 3.96021409e-03],
       [0.00000000e+00, 1.84562709e-03, 1.41997067e-02],
       [0.00000000e+00, 4.72563878e-03, 1.36832986e-02],
       [0.00000000e+00, 4.66894405e-03, 1.69076808e-02],
       [0.00000000e+00, 2.49263644e-03, 2.14094073e-02],
       [0.00000000e+00, 3.06672161e-03, 2.36703008e-02],
       [0.00000000e+00, 0.00000000e+00, 2.19892077e-02],
       [0.00000000e+00, 0.00000000e+00, 2.71498784e-02],
       [0.00000000e+00, 3.91844078e-04, 3.09803132e-02],
       [0.00000000e+00, 0.00000000e+00, 3.11560519e-02],
       [0.00000000e+00, 0.00000000e+00, 3.27254012e-02],
       [4.56575630e-03, 0.00000000e+00, 1.70099996e-02],
       [0.00000000e+00, 0.00000

In [10]:
layer2.forward(activation1.output)

In [31]:
layer2.output.shape

(300, 3)

In [11]:
activation2.forward(layer2.output)

In [12]:
activation2.output

array([[0.33333334, 0.33333334, 0.33333334],
       [0.33331734, 0.3333183 , 0.33336434],
       [0.3332888 , 0.33329153, 0.33341965],
       [0.33325943, 0.33326396, 0.33347666],
       [0.33323312, 0.33323926, 0.33352762],
       [0.33328417, 0.33328718, 0.33342862],
       [0.33318216, 0.33319145, 0.33362636],
       [0.33318278, 0.33319202, 0.33362517],
       [0.33314922, 0.33316055, 0.3336902 ],
       [0.3331059 , 0.33311984, 0.3337743 ],
       [0.3330813 , 0.3330968 , 0.33382186],
       [0.33311027, 0.33312503, 0.33376473],
       [0.3330537 , 0.33307084, 0.33387548],
       [0.33300948, 0.33302936, 0.3339612 ],
       [0.33301342, 0.33303303, 0.33395353],
       [0.33299845, 0.333019  , 0.3339825 ],
       [0.33312678, 0.33318865, 0.3336846 ],
       [0.3329409 , 0.33296496, 0.33409408],
       [0.33299428, 0.33303145, 0.33397427],
       [0.3328737 , 0.33290187, 0.33422446],
       [0.3328757 , 0.33290377, 0.33422053],
       [0.33309552, 0.33318356, 0.33372095],
       [0.