In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [3]:
nnfs.init()

In [8]:
X, y = spiral_data(100,3)

In [9]:
X

array([[-0.00000000e+00,  0.00000000e+00],
       [ 8.09762720e-03,  6.03811583e-03],
       [ 2.87781702e-03,  1.99959949e-02],
       [-1.12273765e-03,  3.02822236e-02],
       [ 2.71612611e-02,  2.99124103e-02],
       [ 1.36994524e-02,  4.86115739e-02],
       [-3.69882886e-03,  6.04930855e-02],
       [ 2.38322304e-03,  7.06668943e-02],
       [ 7.39217624e-02,  3.26422900e-02],
       [ 6.70419633e-02,  6.13990054e-02],
       [ 8.17647278e-02,  5.93091063e-02],
       [ 1.10762931e-01, -8.78932606e-03],
       [ 7.32312277e-02,  9.65896770e-02],
       [ 1.06643260e-01,  7.66182393e-02],
       [ 1.32884428e-01,  4.83703353e-02],
       [ 1.51509717e-01,  1.28316891e-03],
       [ 1.61568522e-01, -3.92358424e-03],
       [ 1.71716437e-01, -5.03438467e-04],
       [ 1.77570865e-01, -3.90696824e-02],
       [ 1.83643028e-01, -5.57513535e-02],
       [ 2.01209754e-01, -1.80775020e-02],
       [ 2.09928200e-01, -3.04230601e-02],
       [ 1.56617656e-01, -1.57650322e-01],
       [ 2.

In [10]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], d

In [22]:
class Layer_Dense :
    def __init__(self,n_inputs,n_neurons):
        self.Weights = 0.10 * np.random.randn(n_inputs,n_neurons)
        self.Biases = np.zeros((1,n_neurons))
    def forward(self,inputs) :
        self.output = np.dot(inputs,self.Weights) + self.Biases

In [17]:
class Activation_ReLU :
    def forward(self,inputs) :
        self.output = np.maximum(0,inputs)

In [23]:
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

In [24]:
layer1.forward(X)

In [25]:
layer1.output

array([[ 0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
         0.0000000e+00],
       [-2.5732856e-04,  1.7287125e-03,  7.9397886e-04, -1.1693799e-03,
        -4.8978822e-05],
       [-6.3581544e-04,  2.4510284e-03,  1.5313919e-04, -1.4877664e-03,
         2.7533644e-03],
       ...,
       [ 1.3376896e-02, -1.4799501e-01, -9.9031106e-02,  1.0554638e-01,
         9.4336234e-02],
       [ 2.0268118e-02, -1.6480626e-01, -9.0999499e-02,  1.1416125e-01,
         4.9092203e-02],
       [ 7.0204022e-03, -1.2972336e-01, -1.0369235e-01,  9.5471144e-02,
         1.3170367e-01]], dtype=float32)

In [27]:
activation1.forward(layer1.output)

In [28]:
activation1.output

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.00172871, 0.00079398, 0.        , 0.        ],
       [0.        , 0.00245103, 0.00015314, 0.        , 0.00275336],
       ...,
       [0.0133769 , 0.        , 0.        , 0.10554638, 0.09433623],
       [0.02026812, 0.        , 0.        , 0.11416125, 0.0490922 ],
       [0.0070204 , 0.        , 0.        , 0.09547114, 0.13170367]],
      dtype=float32)